### ISSUE TITLE
What are people using generator-angular-require for?

### ISSUE THREAD

**Issue by aaronallport** [aaronallport/generator-angular-require#39]
What are folks using this generator for?

Do you use generator-angular-require? If so, what for? How? Why?

I'm keen to show some use cases for it so that a community gets built around this to drive its momentum forward.

Love,

Aaron

**Comment by topping** [comment]
Hi Aaron, thanks for the spectacular work! I am just re-learning JS for the third time in several years. I come from a modular JVM background and am interested in scaffolding that would allow for the modules of the application to be maintained as separate projects, included via Require. I don't know if that's practical, but the goal would be that the application would be built on core assets that define layout in the main module and support modules that could be shared through Bower with wildly different projects. 

For instance, use of a webmail module would start with a 'bower install'. In the build, bower-requirejs would make the module available by reference, then the references would be used inside the main application as required to evoke the functionality of the module.

Besides the obvious benefit of growing an ecosystem of modules, modules might be able to be served from CDN directly. Further, sensitive modules could be stored behind protected paths on the web server, reducing the attack surface area of the application.

I would love to hear any feedback you might have on these ideas!

**Comment by aaronallport** [comment]
Brian,

That sounds interesting! I'd be keen to learn more. Have you got a repo spun up for your project?

Cheers,

Aaron
