### ISSUE TITLE
when I run 'grunt serve', it has an error

### ISSUE THREAD

**Issue by Metoyo** [aaronallport/generator-angular-require#44]
when I run grunt serve, it has an error,
```c
songtaodembp:metoyo songtao$ grunt serve
Running "serve" task

Running "clean:server" (clean) task

Running "wiredep:app" (wiredep) task
Warning: ENOENT, no such file or directory '/Users/songtao/projects/metoyo/app/bower.json' Use --force to continue.

Aborted due to warnings.


Execution Time (2014-09-25 09:27:14 UTC)
loading tasks    3ms  ▇ 1%
clean:server     3ms  ▇ 1%
wiredep:app    212ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 95%
Total 223ms

songtaodembp:metoyo songtao$ 
```

**Comment by aaronallport** [comment]
Does this happen on 0.4.1?

**Comment by VladimirAus** [comment]
I found similar error 
```sh
$ Loading "Gruntfile.js" tasks...ERROR
$ >> Error: Cannot find module 'load-grunt-tasks'
```
version 0.4.2

**Comment by daniele-zurico** [comment]
when I run grunt test the browser close after the test.
karma.conf.js contain this configuration:

    browsers: ['Chrome'],
    singleRun: false

**Comment by lovesh** [comment]
I face the same error as @VladimirAus on master branch which i believe is 0.4.2

**Comment by danpaulsmith** [comment]
I have to manually install grunt-filerev for this generator

**Comment by ihopepeace** [comment]
Version 0.4.2
Error:
<pre>
Loading "Gruntfile.js" tasks...ERROR<br/>
Error: Cannot find module 'load-grunt-tasks'
</pre>

**Comment by ihopepeace** [comment]
@danpaulsmith Can you elaborate.. How you did that?

**Comment by markharding** [comment]
There is a dependency error with grunt-filerev. In package.json change `grunt-filerev` version to `^0.2.1` and then run `npm install`

**Comment by aaronallport** [comment]
This is resolved in https://github.com/aaronallport/generator-angular-require/releases/tag/v1.0.0
