### ISSUE TITLE
Error while installing Fontawesome

### ISSUE THREAD

**Issue by tiefenauer** [aaronallport/generator-angular-require#46]
Hi there
I generated a scaffolding using your generator (latest version of node/grunt/bower/yeoman/generator-angular-require). Everything works fine until I install Fontawesome as a dependency. When running the build I get the following exception:

    Running "requirejs:dist" (requirejs) task
    >> Error: Error: ENOENT, no such file or directory 'c:\Users\Daniel\workspace\test\.tmp\bower_components\fontawesome\fonts\*.js'

Steps to reproduce:
    mkdir test
    cd test
    yo angular-require test (accept all defaults)
    grunt build
    grunt
    bower install fontawesome --save
    grunt

I'm running this on Windows 8.1, tried with Git Bash CLI and cmd. I'm not sure if it is FontAwesome's fault or the generator (I'm pretty new to yeoman). Any idea what causes this error?

**Comment by aaronallport** [comment]
Hi,

Sorry for the delayed response. Have you tried the latest version of the generator (0.4.1)?

If the issue persists, please paste the output to this thread. 

Thanks!

**Comment by GersonYF** [comment]
Hi,

This happened to me a couple of weeks ago, my fix was the next...

requirejs: {
      dist: {
        options: {
          dir: '<%= yeoman.dist %>/scripts/',
          modules: [{
            name: 'main'
          }],
          preserveLicenseComments: false, // remove all comments
          removeCombined: true,
          baseUrl: '.tmp/<%= yeoman.app %>/scripts',
          mainConfigFile: '.tmp/<%= yeoman.app %>/scripts/main.js',
          optimize: 'uglify2',
          uglify2: {
            mangle: false
          },
          paths: {
            'font-awesome': 'empty' //Being this the fix
          }
        }
      }
    }

We tell require to ignore this path!
Let me know if works for you, worked for me!

Best regards!

**Comment by aaronallport** [comment]
This isn't an issue on https://github.com/aaronallport/generator-angular-require/releases/tag/v1.0.0 - or at least I have tried several times to reproduce this and I cannot. Can you test on 1.0.0? Thanks!

**Comment by aaronallport** [comment]
Closed as no response
