### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by gmaggess** [aaronallport/generator-angular-require#47]
Hello,

I've been using your generator for a month and it's been quite helpful. Thanks for the great work.

Nevertheless, since I'm a newbie on Angular, I have a few questions regarding how you structured the scaffolded code.

* I noticed that every Angular component seems to be its own module. For instance, when creating a controller, the angular module is "myApp.controllers.MyController":

```
angular.module('myApp.controllers.MyController', [])
      .controller('MyController', function ($scope) {
}
```

Is there a reason that?

* When generating a new Angular entity, it gets automatically inserted into app.js in a way that it gets loaded in the app initialization. Is there a reason for not lazy loading every component?

* In terms of performance, does requirejs brings a great improvement to angular?

* I've read several articles out there showing how to lazy load controllers and others saying __NOT__ to use requirejs as the AMD framework for Angular. I guess you might have a strong opinion about it. Do you mind shedding some light about it?

Thanks in advance for your time.

Cheers,
George

**Comment by aaronallport** [comment]
George,

Thanks for getting in touch. I'll try to address each of your points separately:

*I noticed that every Angular component seems to be its own module. For instance, when creating a controller, the angular module is "myApp.controllers.MyController". Is there a reason that?*

Personal preference. I prefer to keep everything separate to de-couple as much as possible.

*When generating a new Angular entity, it gets automatically inserted into app.js in a way that it gets loaded in the app initialization. Is there a reason for not lazy loading every component?*

This depends on your individual needs. Yeoman generators are purposefully opinionated, and this one is of the option of bundling up application JS, minifying etc using the RequireJS optimiser. Lazy loading each component means lots of HTTP requests, and bundling removes the need to more HTTP requests. Again, this depends on individual needs.

*In terms of performance, does requirejs brings a great improvement to angular?*

I'd point you to my previous answer for this one too.

*I've read several articles out there showing how to lazy load controllers and others saying NOT to use requirejs as the AMD framework for Angular. I guess you might have a strong opinion about it. Do you mind shedding some light about it?*

Again, it depends on your needs and personal preferences. RequireJS allows you to specify dependencies outside of your angular code such as jQuery, so it can be good for explicitly stating dependencies to ensure that they are available when angular needs them. Thats my personal opinion, but I was using RequireJS before AngularJS came along, and to me it made sense to keep using it, combining the best of both worlds (in my case).

Thanks for taking an interest in my work, and I'm always happy to accept suggestions, or better yet, pull requests!

Cheers,

Aaron
