### ISSUE TITLE
When I run grunt test the browser is closing after the test

### ISSUE THREAD

**Issue by daniele-zurico** [aaronallport/generator-angular-require#49]
npm -v generator-angular-require
1.4.28

    browsers: ['Chrome'],
    // Continuous Integration mode
    // if true, it capture browsers, run tests and exit
    singleRun: false

How I can fix this problem?

**Comment by aaronallport** [comment]
Hi and sorry for the radio silence. I've recently pushed v1.0.0 and don't personally get this issue. Can you re-test on 1.0.0 and let me know if it is still a problem for you? 

Also, are you on Mac/*nix/Windows?

**Comment by aaronallport** [comment]
No response hence closure
