### ISSUE TITLE
Added generator-angular-require to comparison of starters

### ISSUE THREAD

**Issue by dancancro** [aaronallport/generator-angular-require#50]
H Aaron and everyone,

I just came across this project and added it to the following collection of such things that I curate. 
http://www.dancancro.com/comparison-of-angularjs-application-starters

Would any of you like to help fill in the details about what it does?  If so, let me know and I'll make you an editor to the Google doc, or if you prefer, [here](https://docs.google.com/forms/d/1osNL4gHPo3MvGpsp8416SoMJ6wp_k3d4-_2G4VdekoI/viewform) are the questions in survey form.

Thanks,
Dan

**Comment by aaronallport** [comment]
I've done this - sorry for taking so long to do it 0 thats quite the questionnaire you have!

**Comment by dancancro** [comment]
Thank you.

I update the questionnaires quite regularly. The latest versions can be found [here](http://www.dancancro.com/technology-questionnaires/).  There are questionnaires for various types of things. The others are not quite the marathon that the Application Starter one is.  All of it goes into the same collection to make choosing technologies easier for everybody.
