### ISSUE TITLE
Lazy loading controllers

### ISSUE THREAD

**Issue by cristifilip** [aaronallport/generator-angular-require#53]
I might misunderstand some things here...
But, as we build components, I expect that a module will be loaded only when it is accessed. 
Let's say we have: ListCtrl.js + List.html + ListDirective.js  - I was waiting that all of these would be loaded only when I acces the route: /list. 

Is this possible? 

I had installed a clean clone of this and it seems to run like an ordinary app. All javascript files are loaded when I land on the first page.

I have a huge application with many dependencies and I would like to split it in modules, then load a module only if an user requests it.

Thanks!

**Comment by langdonx** [comment]
I had the same question, and I've found it answered here: https://github.com/aaronallport/generator-angular-require/issues/48

I was looking for a stop gap between now and waiting for 1.4's new router (which has promised to support lazy loading).

**Comment by aaronallport** [comment]
Sorry for the late response, but I have answered this before as @langdonx points out. If you need something tailored to your needs, then why not fork and roll your own? I'd happily take in any improvements you come up with :)
