### ISSUE TITLE
when I run 'grunt build', it's has a error

### ISSUE THREAD

**Issue by Metoyo** [aaronallport/generator-angular-require#54]
When I run 'grunt build', it's has a warning, the build command stop work. The waring code: 

> Running "ngAnnotate:dist" (ngAnnotate) task
> Warning: Cannot assign to read only property '$methodName' of false Use --force to continue.
> Aborted due to warnings.
> Execution Time (2015-05-05 07:49:20 UTC)
> wiredep:app        135ms  ▇ 2%
> bower:app          608ms  ▇▇▇▇▇ 10%
> concurrent:dist     4.9s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 78%
> autoprefixer:dist  295ms  ▇▇▇ 5%
> ngAnnotate:dist    273ms  ▇▇ 4%
> Total 6.3s

**Comment by Metoyo** [comment]
I have solved the problem with the command '$ npm install --save-dev grunt-ng-annotate'.

**Comment by aaronallport** [comment]
This is no longer an issue in https://github.com/aaronallport/generator-angular-require/releases/tag/v1.0.0 -- theres a good 4-5 months worth of fixes in there!
