### ISSUE TITLE
JQuery... How to add in the require.config so can load before angular?

### ISSUE THREAD

**Issue by hmendezm** [aaronallport/generator-angular-require#55]
Hi guys, thanks very much for put togther this awesome generator. I am using it and everything is working as expected. the only situation that I have is that I need to load jquery before angular and I have not found a way to do it. Do you have any idea? I know I can add in the.html file but I would like to have the.html only with require.js.

Bests

**Comment by alouiseq** [comment]
Shim object in your require.config allows you to specify the required modules to be loaded first before your module is loaded.

e.g. to load jquery before angular is loaded:
shim: {
        angular: {
            deps: [ 'jquery' ],
            exports: 'angular'
        }
};

**Comment by aaronallport** [comment]
I agree - shim config is your friend here
