### ISSUE TITLE
Path to long in MSBUILD Task UTF-8-Validate

### ISSUE THREAD

**Issue by blairstark** [aaronallport/generator-angular-require#56]
npm version 2.12.1, latest yo, bower

C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targe
ts(308,5): error MSB3491: Could not write lines to file "Release\obj\validation
\validation.tlog\validation.lastbuildstate". The specified path, file name, or
both are too long. The fully qualified file name must be less than 260 characte
rs, and the directory name must be less than 248 characters. [C:\isms.js\tinisp
om\tinspomAngularRequireJs\node_modules\karma\node_modules\socket.io\node_modul
es\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\
utf-8-validate\build\validation.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\bstark\AppData\Roaming\npm\n
ode_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Users\\bstark\\AppData\\Roaming\\npm\\node_modules\
\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\isms.js\tinispom\tinspomAngularRequireJs\node_modules\karma\node
_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\n
ode_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok

**Comment by aaronallport** [comment]
This isn't an issue with the generator per-se, but a limitation of windows. See https://github.com/joyent/node/issues/6960#issuecomment-46704998 - I'd consider using dedupe if you run into this problem a lot. 

Given this isn't an issue with this generator, I'm going to close this issue
