### ISSUE TITLE
Support namespace support for angular module

### ISSUE THREAD

**Issue by divyakumarjain** [aaronallport/generator-angular-require#58]
I have just started using this generator this cool and I started liking this.

As a feature would like to suggest that while creating new angular object it be great to have these objects in the namespace

e.g.
mymodule.directive
mymodule.controller
mymodule.service

at present all the object to directive, controller folder in root.

**Comment by aaronallport** [comment]
I'd fork the repo to create what you need - unless you're asking for this to be an option?

**Comment by divyakumarjain** [comment]
Adding Angular object to namespace which mean adding them to angular module and these module can also have dedicated folders.

Example: When i say "yo angular-require:controller authenticationModule.userCntl" it should generate 'userCntl' controller as part of 'authenticationModule' angular module and inside 'authenticationModule' folder.

**Comment by aaronallport** [comment]
Whilst I can see what you're after, I'd be keen to see a pull request for this if you're keen to take it forward.
