### ISSUE TITLE
RequireJS can't find angularjs and the other angular modules (ngRoute, ngResource)

### ISSUE THREAD

**Issue by figalex** [aaronallport/generator-angular-require#59]
I don't know if I'm missing something, but the main.js configuration only requires angular and its modules by name (without any path) and on index.html these scripts are never loaded. I saw the grunt-wiredep configuration on the gruntfile.js but it only sets index.html as src and inside index.html there's no ```<!-- bower:js -->``` tag to load these scripts, there is only a ```<!-- bower:css -->``` tag. This is on version 1.0.0.

**Comment by aaronallport** [comment]
Do you have an issue in particular or an error message? If so can you post it please?

**Comment by figalex** [comment]
It just displays ```http://localhost:3000/scripts/angular.js Not found 404```.

I don't know if I'm wrong, but I expected to run the generator and after that without doing anything else just run ```grunt serve``` and have a running application. Is this the expected result or after running the generator I should configure the paths for each of the angular modules?

**Comment by aaronallport** [comment]
No you're right, you should be able to run grunt build and grunt serve and you should have a working app.

What version of the generator are you using?

**Comment by figalex** [comment]
Version 1.0.0

**Comment by juliangut** [comment]
The same is happening to me with version 1.0.0

**Comment by aaronallport** [comment]
This is now available in v1.0.1
