### ISSUE TITLE
angular-ui-router addition

### ISSUE THREAD

**Issue by juliangut** [aaronallport/generator-angular-require#60]
Wouldn't it be nice to add `angular-ui-router` to the list of available bower components, such as `angular-animate`, `angular-loader`, etc ?

**Comment by aaronallport** [comment]
How would you see this working? Given that ngRoute is the preferred module at present, I'd effectively have to write two sets of files to be tokenised. I'll look into this when I get some downtime.

**Comment by juliangut** [comment]
You can set a config option and use it in the files to conditionally use ngroute or uirouter. 

Have a look at this project of mine: https://github.com/juliangut/generator-barephp/blob/master/app/templates/_gitattributes I heavily use this approach on that generator
