### ISSUE TITLE
Avoid combining script to single js file

### ISSUE THREAD

**Issue by ShortFatBaldHairyMan** [aaronallport/generator-angular-require#62]
I am creating enterprise level application. If browser request all js file on first load, page will take lot of time to load. How can generate a build which will call js file on need basis so my site's initial load time will get decrease?

Right now grunt build generate combine js file.

**Comment by aaronallport** [comment]
I suggest you change your generated gruntfile to omit the requirejs task and instead do a copy of the source files. You'll need to update the reference to the javascript in the main html file thats generated too. Feel free to enhance via a pull request though!
