### ISSUE TITLE
Getting dependency errors of grunt & karma

### ISSUE THREAD

**Issue by sunrayravi** [aaronallport/generator-angular-require#66]
UNMET PEER DEPENDENCY grunt@0.4.x
├─┬ grunt-karma@0.10.1 
│ └── lodash@2.4.2 
├── UNMET PEER DEPENDENCY jasmine-core@*
├── UNMET PEER DEPENDENCY karma@~0.12.0
........
UNMET PEER DEPENDENCY phantomjs@>=1.9
└── UNMET PEER DEPENDENCY requirejs@~2.1

**Comment by aaronallport** [comment]
If you have them installed globally (grunt and phantomjs), then all should be well (this generator specifies them as peer dependencies, which means you should install them globally). If you have grunt and phantomjs installed already, then this is likely a bug in NPM, not this generator. See https://github.com/yeoman/generator-angular/issues/1205 where this happened on generator-angular.
