### ISSUE TITLE
use the generator,show "Uncaught ReferenceError: ngCookies is not defined"

### ISSUE THREAD

**Issue by dounine** [aaronallport/generator-angular-require#71]
"Uncaught ReferenceError: ngCookies is not defined" for app.js
![image](https://cloud.githubusercontent.com/assets/7344514/14388242/cecd77cc-fddf-11e5-8e0a-656a04d58207.png)

![image](https://cloud.githubusercontent.com/assets/7344514/14388279/f95132f4-fddf-11e5-97ca-6b8d06d4555c.png)

thank!

**Comment by lckmalhotra** [comment]
return angular.module('requireApp', [
    'requireApp.controllers.MainCtrl',
    'requireApp.controllers.AboutCtrl',
    'ngRoute',
    'ngCookies',
    'ngSanitize',
    'ngResource',
    'ngAnimate',
    'ngTouch'
/*angJSDeps*/])

Add dependency in ' ' your issue will resolved.

**Comment by DScarfo2** [comment]
To add to pderopcruz correct solution, you need to add the single quote, around each of the dependencies to resolve.  The angular-require generator creates them without.
